# Generated by Django 5.0.3 on 2024-03-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='state',
            field=models.CharField(choices=[
                                        ('edit', 'Edit State'),
                                        ('ready', 'Ready State'),
                                        ('approving', 'Approving State'),
                                        ('finalized', 'Finalized State')
                                    ], default='edit', max_length=20),
        ),
    ]
